-- MySQL Script generated by MySQL Workbench
-- 10/09/15 22:24:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema universities
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `universities` ;

-- -----------------------------------------------------
-- Schema universities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universities` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `universities` ;

-- -----------------------------------------------------
-- Table `universities`.`Universities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Universities` ;

CREATE TABLE IF NOT EXISTS `universities`.`Universities` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `universities`.`Faculties` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Departments` ;

CREATE TABLE IF NOT EXISTS `universities`.`Departments` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`Persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Persons` ;

CREATE TABLE IF NOT EXISTS `universities`.`Persons` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Courses` ;

CREATE TABLE IF NOT EXISTS `universities`.`Courses` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`FacultyInstances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`FacultyInstances` ;

CREATE TABLE IF NOT EXISTS `universities`.`FacultyInstances` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `FacultyId` INT NOT NULL COMMENT '',
  `UniversityId` INT NOT NULL COMMENT '',
  `Faculties_Id` INT NOT NULL COMMENT '',
  `Universities_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fk_FacultyInstances_Faculties_idx` (`Faculties_Id` ASC)  COMMENT '',
  INDEX `fk_FacultyInstances_Universities1_idx` (`Universities_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_FacultyInstances_Faculties`
    FOREIGN KEY (`Faculties_Id`)
    REFERENCES `universities`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacultyInstances_Universities1`
    FOREIGN KEY (`Universities_Id`)
    REFERENCES `universities`.`Universities` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`DepartmentInstances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`DepartmentInstances` ;

CREATE TABLE IF NOT EXISTS `universities`.`DepartmentInstances` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DepartementId` INT NOT NULL COMMENT '',
  `FacultyInstanceId` INT NOT NULL COMMENT '',
  `Departments_Id` INT NOT NULL COMMENT '',
  `FacultyInstances_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fk_DepartmentInstances_Departments1_idx` (`Departments_Id` ASC)  COMMENT '',
  INDEX `fk_DepartmentInstances_FacultyInstances1_idx` (`FacultyInstances_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_DepartmentInstances_Departments1`
    FOREIGN KEY (`Departments_Id`)
    REFERENCES `universities`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DepartmentInstances_FacultyInstances1`
    FOREIGN KEY (`FacultyInstances_Id`)
    REFERENCES `universities`.`FacultyInstances` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`CourseInstances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`CourseInstances` ;

CREATE TABLE IF NOT EXISTS `universities`.`CourseInstances` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CourseId` INT NOT NULL COMMENT '',
  `DepartementInstaceId` INT NOT NULL COMMENT '',
  `Courses_Id` INT NOT NULL COMMENT '',
  `DepartmentInstances_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fk_CourseInstances_Courses1_idx` (`Courses_Id` ASC)  COMMENT '',
  INDEX `fk_CourseInstances_DepartmentInstances1_idx` (`DepartmentInstances_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_CourseInstances_Courses1`
    FOREIGN KEY (`Courses_Id`)
    REFERENCES `universities`.`Courses` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CourseInstances_DepartmentInstances1`
    FOREIGN KEY (`DepartmentInstances_Id`)
    REFERENCES `universities`.`DepartmentInstances` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Students` ;

CREATE TABLE IF NOT EXISTS `universities`.`Students` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PersonId` INT NOT NULL COMMENT '',
  `FacultyInstanceId` INT NOT NULL COMMENT '',
  `Persons_Id` INT NOT NULL COMMENT '',
  `FacultyInstances_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fk_Students_Persons1_idx` (`Persons_Id` ASC)  COMMENT '',
  INDEX `fk_Students_FacultyInstances1_idx` (`FacultyInstances_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_Persons1`
    FOREIGN KEY (`Persons_Id`)
    REFERENCES `universities`.`Persons` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_FacultyInstances1`
    FOREIGN KEY (`FacultyInstances_Id`)
    REFERENCES `universities`.`FacultyInstances` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`StudentCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`StudentCourses` ;

CREATE TABLE IF NOT EXISTS `universities`.`StudentCourses` (
  `CourseInstanceId` INT NOT NULL COMMENT '',
  `StudentInstanceId` INT NOT NULL COMMENT '',
  `CourseInstances_Id` INT NOT NULL COMMENT '',
  `Students_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`CourseInstanceId`, `StudentInstanceId`)  COMMENT '',
  INDEX `fk_StudentCourses_CourseInstances1_idx` (`CourseInstances_Id` ASC)  COMMENT '',
  INDEX `fk_StudentCourses_Students1_idx` (`Students_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_StudentCourses_CourseInstances1`
    FOREIGN KEY (`CourseInstances_Id`)
    REFERENCES `universities`.`CourseInstances` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentCourses_Students1`
    FOREIGN KEY (`Students_Id`)
    REFERENCES `universities`.`Students` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`Professors` ;

CREATE TABLE IF NOT EXISTS `universities`.`Professors` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PersonId` INT NOT NULL COMMENT '',
  `DepartementInstaceId` INT NOT NULL COMMENT '',
  `Persons_Id` INT NOT NULL COMMENT '',
  `DepartmentInstances_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fk_Professors_Persons1_idx` (`Persons_Id` ASC)  COMMENT '',
  INDEX `fk_Professors_DepartmentInstances1_idx` (`DepartmentInstances_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_Professors_Persons1`
    FOREIGN KEY (`Persons_Id`)
    REFERENCES `universities`.`Persons` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_DepartmentInstances1`
    FOREIGN KEY (`DepartmentInstances_Id`)
    REFERENCES `universities`.`DepartmentInstances` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`PersonTitles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`PersonTitles` ;

CREATE TABLE IF NOT EXISTS `universities`.`PersonTitles` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` NVARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`ProfessorTitles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`ProfessorTitles` ;

CREATE TABLE IF NOT EXISTS `universities`.`ProfessorTitles` (
  `ProfessorId` INT NOT NULL COMMENT '',
  `PersonTitleId` INT NOT NULL COMMENT '',
  `PersonTitles_Id` INT NOT NULL COMMENT '',
  `Professors_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ProfessorId`, `PersonTitleId`)  COMMENT '',
  INDEX `fk_ProfessorTitles_PersonTitles1_idx` (`PersonTitles_Id` ASC)  COMMENT '',
  INDEX `fk_ProfessorTitles_Professors1_idx` (`Professors_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_ProfessorTitles_PersonTitles1`
    FOREIGN KEY (`PersonTitles_Id`)
    REFERENCES `universities`.`PersonTitles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorTitles_Professors1`
    FOREIGN KEY (`Professors_Id`)
    REFERENCES `universities`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universities`.`ProfessorCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universities`.`ProfessorCourses` ;

CREATE TABLE IF NOT EXISTS `universities`.`ProfessorCourses` (
  `CourseInstanceId` INT NOT NULL COMMENT '',
  `ProfessorId` INT NOT NULL COMMENT '',
  `Professors_Id` INT NOT NULL COMMENT '',
  `CourseInstances_Id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`CourseInstanceId`, `ProfessorId`)  COMMENT '',
  INDEX `fk_ProfessorCourses_Professors1_idx` (`Professors_Id` ASC)  COMMENT '',
  INDEX `fk_ProfessorCourses_CourseInstances1_idx` (`CourseInstances_Id` ASC)  COMMENT '',
  CONSTRAINT `fk_ProfessorCourses_Professors1`
    FOREIGN KEY (`Professors_Id`)
    REFERENCES `universities`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorCourses_CourseInstances1`
    FOREIGN KEY (`CourseInstances_Id`)
    REFERENCES `universities`.`CourseInstances` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
